### ISSUE TITLE
freeBuffer is not part of released minigrafx api

### ISSUE THREAD

**Issue by ptman** [ThingPulse/espaper-client#22]
which makes it quite hard to compile

**Comment by jwende** [comment]
same issue on my end - any way to resolve this ?

**Comment by squix78** [comment]
Yes you are right, I made changes to the MiniGrafx library which are not released yet, but the espaper-client is using these changes. I hope to fix it very soon. You could however use the unreleased version of MiniGrafx directly from the github repository: https://github.com/thingpulse/minigrafx

**Comment by jwende** [comment]
but it is not in the main branch yet - isn't it ?

**Comment by marcelstoer** [comment]
MiniGrafx will be released soon and this issue would belong into that repository -> closing
