### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by jwende** [ThingPulse/espaper-client#23]
just reloading the current code on my clients and I've got:
- Connecting to www.espaper.com:443*** Can't connect. ***
Any point I might look for ?
J.

**Comment by squix78** [comment]
I restarted the server this morning. Any improvement?

**Comment by jwende** [comment]
tried some hours ago ...  what id do I have to take 
- the device name (thats what I have to specify on the web site)
or
- the generated device UUID ?

if I take the UUID and try it via the web browser a 404 is returned - but if I take the device name an json error message is returned 

J.
