### ISSUE TITLE
No screen - no config

### ISSUE THREAD

**Issue by jwende** [ThingPulse/espaper-client#24]
I used to build a new firmware with platform.io and anything seems to be broken:
- no display at a ll (black screen)
- if starting in config mode no html page is returned to my browser 

any hint ?
J.

**Comment by squix78** [comment]
Hi Jörg
We are currently working on the next generation of espaper-client and server. In this context we might have broken one thing or two, sorry for the inconvenience. Would you be interested in test our new version?

**Comment by jwende** [comment]
Hi Daniel
I just have some free time ... so why not :-D
J.
