### ISSUE TITLE
Test speed (i.e. battery life) improvements with persistent BearSSL sessions

### ISSUE THREAD

**Issue by marcelstoer** [ThingPulse/espaper-client#25]
https://arduino-esp8266.readthedocs.io/en/latest/esp8266wifi/bearssl-client-secure-class.html?highlight=rtc#tls-sessions

With ESP8266 Arduino-core 2.5.0 we may be able to serialize the BearSSL::Session object to RTC RAM and restore it before trying to (re)connect. Should give a significant speed (and thus battery life) boost.

**Comment by squix78** [comment]
In this context I would love if we could extend the headers the client sends by a field which measures the full awake time of the last cycle.

**Comment by marcelstoer** [comment]
-> #26

**Comment by marcelstoer** [comment]
We should keep this open and also consider the other recommendations in that great documentation page.

> it is recommended that all TLS/SSL sketches to run at 160 Mhz and not the default 80 Mhz.

wrt energy: higher CPU speed vs. shorter air time
