### ISSUE TITLE
Weather Widget

### ISSUE THREAD

**Issue by schroepfer** [ThingPulse/espaper-client#32]
Hello,
i want to user the weather widget.
I filled the API-Key and City Name, butt all my known City-IDs doesn't work!?
I get only Zürich.  ;-)
Regards
Jürgen

**Comment by squix78** [comment]
Hi Jürgen. 
So just to be sure, you have a valid OpenWeatherMap key and tried to enter a city name but the lookup didn't give you a result? Can you give me an example city name you tried?

Thank you,
Dani

**Comment by schroepfer** [comment]
Yes, in other applications the key works. I tried "Melsungen".
Regards
Jürgen

Daniel Eichhorn <notifications@github.com> schrieb am So., 10. März 2019,
15:43:

**Comment by squix78** [comment]
Hi Jürgen

Thank you so much for pointing this out. Can you please check again? I
think I fixed it now...

Kind regards,
Daniel

Am So., 10. März 2019 um 16:04 Uhr schrieb schroepfer <
notifications@github.com>:

**Comment by schroepfer** [comment]
No, it doesn't work:

[image: Screen Editor 2019-03-10 19-15-48.jpg]
All fields are green, City ID is red.
When i use the widget i get Zürich.


Am So., 10. März 2019 um 19:03 Uhr schrieb Daniel Eichhorn <
notifications@github.com>:

**Comment by squix78** [comment]
There is something fishy indeed. The first time I open the dialog I get:
![image](https://user-images.githubusercontent.com/716822/54090245-5dc47680-4372-11e9-8c8d-3f5b739d289f.png)
Then afterwards:
![image](https://user-images.githubusercontent.com/716822/54090250-6b79fc00-4372-11e9-9156-9a1f268a61ba.png)

I can't see the image you attached. Does it look the same?

**Comment by schroepfer** [comment]
Yes, exactly.

Daniel Eichhorn <notifications@github.com> schrieb am So., 10. März 2019,
20:24:
