### ISSUE TITLE
Can't Set Weather Widget City Name

### ISSUE THREAD

**Issue by wabmester** [ThingPulse/espaper-client#36]
I'm able to use the weather widget, and it correctly fetches the weather data, but two related issues:

1) My city name is long ("Bainbridge Island") and it wraps around, over the temperature.

2) I can't edit the city name in the app settings.   It keeps getting overwritten by the json name associated with the city id (5816320).    This may be similar to another open issue where the city name field was misbehaving.

**Comment by datacute** [comment]
I've just started using this today, and discovered that you can 'ungroup' the elements, then double click on the city name element, and change it to be constant text instead of read from the data.

**Comment by wabmester** [comment]
Nice work-around.   When I tried it, I needed to delete the city name element and replace it with static text, otherwise it still reverted to the fetched name.

**Comment by marcelstoer** [comment]
Thanks for raising this issue. We're not sure what the best option is here but it _is_ probably not intuitive that the city name you configured is not the one displayed. So far, the sole purpose of that configured name is to look up the location id that OWM needs (their API also supports query by name or lat/long but results are then ambiguous).

Do you think we should change that?

The procedure to edit it in your screen is as follows.

**Ungroup the widget**

**Double-click the city name**
![Screenshot_2019-09-16_at_09_44_19](https://user-images.githubusercontent.com/624195/64941847-f2e78100-d867-11e9-88c5-91048384ccdf.jpg)
**Replace the ${} expression with static content**
<img width="401" alt="Screenshot 2019-09-16 at 09 44 39" src="https://user-images.githubusercontent.com/624195/64941880-04c92400-d868-11e9-902c-6305f9007788.png">
**Save**
<img width="210" alt="Screenshot 2019-09-16 at 09 45 28" src="https://user-images.githubusercontent.com/624195/64941897-0db9f580-d868-11e9-90bb-43204c445c7a.png">
