### ISSUE TITLE
Display is all messed up since few days

### ISSUE THREAD

**Issue by faquin** [ThingPulse/espaper-client#47]
Since few days (couple of weeks maybe), the display is all wrong. 
However the device is correctly fetching data from espaper.com. At least I can see it connects every 10min.
I tried to charge the battery, to reboot the device, to no avail. Any idea what could go wrong?
Should I reflash the firmware?
![20200128_072803](https://user-images.githubusercontent.com/12707798/73248843-f692f900-41b3-11ea-8fbd-8d440f7007c7.jpg)

**Comment by marcelstoer** [comment]
We're tracking this at https://support.thingpulse.com/1182/display-is-all-messed-up
