### ISSUE TITLE
idea: barcode for guest wlan

### ISSUE THREAD

**Issue by jwende** [ThingPulse/espaper-client#7]
generate a barcode on the server that can be scanned and used on wifi enabled devices (ipad, phones) to connect to your guest wlan

**Comment by squix78** [comment]
Hi Joerg

Interesting idea! Can you point me to a specification or a name of this feature? I wasn't aware that you could scan QR(?) codes to set the WiFi credentials. One implication though: your (guest) WLAN credentials would be stored in the cloud...

**Comment by jwende** [comment]
German web articles: 
http://praxistipps.chip.de/wlan-zugang-per-qr-code-teilen_20247
https://www.smart-wohnen.de/haus-garten/artikel/per-qr-code-wifi-schnell-und-sicher-freigeben/
https://www.heise.de/ct/ausgabe/2016-10-Raspberry-Pi-als-Gaeste-WLAN-Automat-3185167.html
